import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import LibreriaProductoCliente.LibreriaCliente;
import LibreriaProductoCliente.LibreriaProducto;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

public class InterfazProductoCliente extends JFrame {
    private JPanel panelInicial;
    private JLabel lbNumeroSerie;
    private JLabel lbProducto;
    private JLabel lbNombre;
    private JLabel lbPrecio;
    private JTextField txtNumeroSerie;
    private JTextField txtNombreProducto;
    private JTextField txtPrecio;
    private JTextField txtNumeroCliente;
    private JTextField txtNombreCliente;
    private JTextField txtTelefono;
    private JLabel lbNumeroCliente;
    private JLabel lbNombreCliente;
    private JLabel lbTelefono;
    private JLabel lbInformacion;
    private JTextArea txtareaInformacion;
    private JPanel panelProducto;
    private JPanel panelCliente;
    private JPanel panelInformacion;
    private JButton btnGuardarProducto;
    private JButton btnGuardarCliente;
    private JButton btnMostradProducto;
    private JButton btnMostrarCliente;

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelInicial = new JPanel();
        panelInicial.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelProducto = new JPanel();
        panelProducto.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelInicial.add(panelProducto, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lbProducto = new JLabel();
        lbProducto.setText("Producto");
        panelProducto.add(lbProducto, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lbNumeroSerie = new JLabel();
        lbNumeroSerie.setText("Número de serie:");
        panelProducto.add(lbNumeroSerie, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNumeroSerie = new JTextField();
        panelProducto.add(txtNumeroSerie, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtNombreProducto = new JTextField();
        panelProducto.add(txtNombreProducto, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lbNombre = new JLabel();
        lbNombre.setText("Nombre:");
        panelProducto.add(lbNombre, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPrecio = new JTextField();
        panelProducto.add(txtPrecio, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lbPrecio = new JLabel();
        lbPrecio.setText("Precio:");
        panelProducto.add(lbPrecio, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelCliente = new JPanel();
        panelCliente.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelInicial.add(panelCliente, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Cliente");
        panelCliente.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lbNumeroCliente = new JLabel();
        lbNumeroCliente.setText("Numero de Cliente:");
        panelCliente.add(lbNumeroCliente, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNumeroCliente = new JTextField();
        txtNumeroCliente.setText("");
        panelCliente.add(txtNumeroCliente, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lbNombreCliente = new JLabel();
        lbNombreCliente.setText("Nombre:");
        panelCliente.add(lbNombreCliente, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNombreCliente = new JTextField();
        panelCliente.add(txtNombreCliente, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lbTelefono = new JLabel();
        lbTelefono.setText("Teléfono:");
        panelCliente.add(lbTelefono, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtTelefono = new JTextField();
        panelCliente.add(txtTelefono, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        panelInformacion = new JPanel();
        panelInformacion.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelInicial.add(panelInformacion, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lbInformacion = new JLabel();
        lbInformacion.setText("Información");
        panelInformacion.add(lbInformacion, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtareaInformacion = new JTextArea();
        panelInformacion.add(txtareaInformacion, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        btnGuardarProducto = new JButton();
        btnGuardarProducto.setText("Guardar");
        panelInicial.add(btnGuardarProducto, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnGuardarCliente = new JButton();
        btnGuardarCliente.setText("Guardar ");
        panelInicial.add(btnGuardarCliente, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnMostradProducto = new JButton();
        btnMostradProducto.setText("Mostrar Productos");
        panelInicial.add(btnMostradProducto, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnMostrarCliente = new JButton();
        btnMostrarCliente.setText("Mostrar Clientes");
        panelInicial.add(btnMostrarCliente, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelInicial;
    }

    ArrayList<LibreriaProducto> productos = new ArrayList<>();
    ArrayList<LibreriaCliente> clientes = new ArrayList<>();
    int contador = 0;
    int contador2 = 0;

    public void metodoActionListener() {
        btnGuardarProducto.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String numeroSerie = txtNumeroSerie.getText();
                String nombreProducto = txtNombreProducto.getText();
                float precio = Float.parseFloat(txtPrecio.getText());
                productos.add(new LibreriaProducto(nombreProducto, numeroSerie, precio));
            }
        });
        btnGuardarCliente.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String numeroCliente = txtNumeroCliente.getText();
                String nombreCliente = txtNombreCliente.getText();
                String telefono = txtTelefono.getText();
                clientes.add(new LibreriaCliente(nombreCliente, numeroCliente, telefono));
            }
        });
        btnMostradProducto.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String todo = "Número de serie: ";
                todo = todo + productos.get(contador).getNumeroSerie() + "\nNombre del Producto: " + productos.get(contador).getNombreProducto() + "\nPrecio: $ " + productos.get(contador).getPrecio();
                txtareaInformacion.setText(todo);
                contador = contador + 1;
            }
        });
        btnMostrarCliente.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String todo = "Número de cliente: ";
                todo = todo + clientes.get(contador2).getNuemroCliente() + "\nNombre del Cliente: " + clientes.get(contador2).getNombreCliente() + "\nTeléfono del cliente: " + clientes.get(contador2).getTelefono();
                txtareaInformacion.setText(todo);
                contador2 = contador2 + 1;
            }
        });
    }

    public InterfazProductoCliente() {
        $$$setupUI$$$();
        $$$getRootComponent$$$();
        metodoActionListener();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setContentPane(panelInicial);
        this.setSize(700, 700);
        this.setLocationRelativeTo(null);
    }

    public static void main(String args[]) {
        InterfazProductoCliente ventana = new InterfazProductoCliente();
        ventana.setVisible(true);
    }
}
